// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'configure this app with FlutterFire CLI for full multi-platform support.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMmkZaysmTxMMCczETf9l1g0oTadS7v7M',
    appId: '1:668168532890:android:8232661a4a50188e3dc023',
    messagingSenderId: '668168532890',
    projectId: 'shreerajmandir-820c7',
    storageBucket: 'shreerajmandir-820c7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ_3YIJEESDU3IwY5q9sJvFVZiKWFNtQc',
    appId: '1:668168532890:web:740c67d3939887183dc023',
    messagingSenderId: '668168532890',
    projectId: 'shreerajmandir-820c7',
    authDomain: 'shreerajmandir-820c7.firebaseapp.com',
    storageBucket: 'shreerajmandir-820c7.firebasestorage.app',
    measurementId: 'G-STZZPKFEBJ',
  );

}